baseURL: "https://lakshgupta.github.io/"
languageCode: "en-us"
title: "Laksh Gupta"
defaultContentLanguage: en
permalinks:
  posts: /posts/:title/

pagination:
  pagerSize: 5

outputs:
  home:
    - HTML
    - RSS

theme:
  - github.com/nodejh/hugo-theme-mini

params:
  author: "Laksh Gupta"
  bio: "Software Engineer"
  description: "Personal blog about machine learning and related topics"
  enableRSS: true
  enableComments: false
  showToc: true
  social: []

taxonomies:
  social: social

markup:
  highlight:
    guessSyntax: true
  goldmark:
    renderer:
      unsafe: true

# Add other settings as needed
